### ISSUE TITLE
unable to go-get: unrecognized import path "logger"

### ISSUE THREAD

**Issue by mewmew** [streambinder/spotitube#37]
Thanks for publishing the spotitube command!

I tried to go-get spotitube, but got stuck at the following error:

```
package github.com/streambinder/spotitube/src/gui
	imports logger: unrecognized import path "logger" (import path does not begin with hostname)
package github.com/streambinder/spotitube/src/gui
	imports system: unrecognized import path "system" (import path does not begin with hostname)
```

Similar errors are given for:

```
package github.com/streambinder/spotitube/src/main
	imports gui: unrecognized import path "gui" (import path does not begin with hostname)
package github.com/streambinder/spotitube/src/main
	imports spotify: unrecognized import path "spotify" (import path does not begin with hostname)
package github.com/streambinder/spotitube/src/main
	imports track: unrecognized import path "track" (import path does not begin with hostname)
package github.com/streambinder/spotitube/src/main
	imports youtube: unrecognized import path "youtube" (import path does not begin with hostname)
```

**Comment by streambinder** [comment]
My fault: this project cannot be built using standard `go get`, as it contains stuff to be manipulated before being effectively compiled (e.g. apply my - or custom - Spotify app ID and secrets, or Genius ones, over source files).
If you want to compile it yourself, please, look at: https://github.com/streambinder/spotitube#build-it-yourself (keep in mind: you need to create a Spotify recognized app and obtain ID and secrets; also, if you want Genius lyrics, you need a Genius key - and therefore, an account). Otherwise, you can find pre-compiled files at: https://github.com/streambinder/spotitube/releases/latest .

**Comment by mewmew** [comment]
Thanks for the info!
